let subject1=["Tamil","English"];
let subject2=["Maths","Science","Social"];
console.log("original array1 :",subject1);
console.log("original array2 :",subject2);
console.log("length of the array1 is "+subject1.length);
console.log("length of the array2 is "+subject2.length);
console.log("method : array1.concat(array2)");
let result=subject1.concat(subject2);
console.log("change in array : ",result);
console.log("return: length of array after concat() is "+result.length);